Add Additional Role Claims Functionality
skoruba/IdentityServer4.Admin pull request #465
Opened 2020-01-17 20:34 UTC by AksharX

2020-01-20 13:06 UTC, skoruba commented
Thanks for your PR, I will check it. 👍

2020-12-01 11:30 UTC, ruzanowski commented
That's good input, however, we might add UI to that 👍 
@AksharX possible to resolve conflicts and add simple management to make it fully functional?

2020-12-04 12:39 UTC, ruzanowski commented on src/Skoruba.IdentityServer4.Admin.BusinessLogic.Identity/Services/IdentityService.cs
> +            await AuditEventLogger.LogEventAsync(new RoleClaimDeletedFromRolesEvent(roleClaimType, roleIds));
Wrong event. Should be: RoleClaimAddedToRolesEvent

2020-12-04 13:09 UTC, ruzanowski commented on src/Skoruba.IdentityServer4.Admin.BusinessLogic.Identity/Services/Interfaces/IIdentityService.cs
> +        Task<int> DeleteClaimForRolesAsync(List<string> roleIds, string roleClaimType);
IList

2020-12-04 15:32 UTC, ruzanowski requested changes

2020-12-04 15:32 UTC, ruzanowski commented on src/Skoruba.IdentityServer4.Admin.EntityFramework.Identity/Repositories/IdentityRepository.cs
> +                where rc.ClaimType.Equals(roleClaimType) && roleIds.Contains(r.Id.ToString())
roleIds.Contains(r.Id.ToString()) in EFCore3.1 is not translated.

try: roleIds.Contains(((string)(object)r.Id))

2021-06-11 15:25 UTC, closed without merging